# Generated by Django 3.0 on 2022-12-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prog', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_kind', models.TextField(blank=True)),
                ('info_infsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_infsource', to='info.Infsource')),
                ('prog_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_package', to='prog.Package')),
            ],
            options={
                'ordering': ['prog_package', 'info_infsource', 'connection_kind'],
            },
        ),
    ]
