# Generated by Django 3.0 on 2022-12-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20221211_2126'),
        ('inter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_kind', models.TextField(blank=True)),
                ('first_info_infsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_info_infsource', to='info.Infsource')),
                ('second_info_infsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_info_infsource', to='info.Infsource')),
            ],
            options={
                'ordering': ['first_info_infsource', 'second_info_infsource', 'connection_kind'],
            },
        ),
    ]
