# Generated by Django 3.0 on 2022-12-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20221211_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='infsource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_infsource', to='info.Infsource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_edition', to='info.Edition'),
        ),
    ]
