# Generated by Django 3.0 on 2022-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20221211_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.TextField(blank=True),
        ),
    ]
