# Generated by Django 3.0 on 2022-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_resource_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='infsource',
            name='license_type',
            field=models.TextField(blank=True),
        ),
    ]
